name: Test

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/oven/bun:1
    steps:
      - name: Run tests
        run: bun test
