name: Test

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/catthehacker/ubuntu:act-22.04
    steps:
      - name: Checkout
        uses: https://gitea.com/actions/checkout@v4

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Run tests
        run: bun test
